<?php

/*$servidor = "bbetfootball.online";
$user = "bbetxfub_admin";
$password = ",NN7QZ.03g+b";
$database = "bbetxfub_data";*/

$servidor = "localhost";
$user = "root";
$password = "";
$database = "apuestas";

$data = ""; 
$usuario = "";

function sqlconector($consulta) {
  $conexion = mysqli_connect($GLOBALS["servidor"], $GLOBALS["user"], $GLOBALS["password"], $GLOBALS["database"]);
  if (!$conexion) {
    die("Failed to connect to Data: " . mysqli_connect_error());
  }
  
  $resultado = mysqli_query($conexion, $consulta);
  
  if (!$resultado) {
      die("Error in query: " . mysqli_error($conexion));
  }
  
  mysqli_close($conexion);
  return $resultado;
}

function row_sqlconector($consulta) {
  $row = array();
	$conexion = @mysqli_connect($GLOBALS["servidor"],$GLOBALS["user"],$GLOBALS["password"],$GLOBALS["database"]);
  if (!$conexion) {
    echo "Refresh page, Failed to connect to Data: " . mysqli_connect_error();
    exit();
  }else{
    $resultado = mysqli_query($conexion, $consulta);
    if($resultado){
  		$row = mysqli_fetch_assoc($resultado);
  	}
  	mysqli_close($conexion);
  }
	return $row;
}

function array_sqlconector($consulta){
  $obj= array();
  $resultado = sqlconector($consulta);
  if($resultado){
    while($row = mysqli_fetch_assoc($resultado)){
      $obj[]=$row;
    }
  }
  return $obj;
}

if( isset($_GET['parche']) ){
/* APLICA MODIFICACIONES DE ULTIMA HORA A LA BASE DE DATOS Y SISTEMA
ESCRIBE AQUI LA LOGICA..
*/  

  echo "Parche Aplicado Con Exito..!<br><br><a href='index'>Ir al Inicio</a>";
}

if( isset($_GET['install']) ){

      sqlconector("CREATE TABLE IF NOT EXISTS DATOS (
        ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        MONEDA VARCHAR(10) DEFAULT 'BTCUSDT',
        ASSET VARCHAR(10) DEFAULT 'BTC',
        PAR VARCHAR(10) DEFAULT 'USDC',
        BALANCE_ASSET DECIMAL(16,8) NOT NULL DEFAULT 0.00,
        PRECIO_VENTA DECIMAL(16,8) NOT NULL DEFAULT 0.00,
        PANTE DECIMAL(16,8) NOT NULL DEFAULT 0.00,
        ACTIVO INT DEFAULT 0,
        ULTIMAVENTA decimal(16,5) NOT NULL DEFAULT '0.00000'
      )");

    sqlconector("CREATE TABLE IF NOT EXISTS PARAMETROS (
      ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
      CAPITAL DECIMAL(16,8) NOT NULL DEFAULT 0.00,
      ESCALONES INT DEFAULT 4,
      INVXCOMPRA DECIMAL(16,8) NOT NULL DEFAULT 0.00,
      DISPONIBLE DECIMAL(16,8) NOT NULL DEFAULT 0.00,
      GANANCIA DECIMAL(16,8) NOT NULL DEFAULT 0.00,
      PERDIDA DECIMAL(16,8) NOT NULL DEFAULT 0.00,
      IMPUESTO DECIMAL(16,8) NOT NULL DEFAULT 0.02,
      LOCAL INT DEFAULT 1,
      BINANCE INT DEFAULT 0,
      APIKEY VARCHAR(255),
      SECRET VARCHAR(255),
      PUNTOS DECIMAL(16,8) NOT NULL DEFAULT 0.00,
      DATOS JSON,
      GRAFICO int(11) DEFAULT '0'  
    )");

    sqlconector("CREATE TABLE IF NOT EXISTS PRICES (
      ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
      FECHA DATE DEFAULT CURRENT_DATE,
      MONEDA VARCHAR(10) DEFAULT 'BTCUSDT',
      DATOS JSON,
      ACTUAL DECIMAL(16,8) NOT NULL DEFAULT 0.00,
      ARRIBA DECIMAL(16,8) NOT NULL DEFAULT 0.00,
      ABAJO DECIMAL(16,8) NOT NULL DEFAULT 0.00,
      BAJISTA INT DEFAULT 0,
      ALCISTA INT DEFAULT 0,
      VERDE INT DEFAULT 0,
      NARANJA INT DEFAULT 0,
      ROJO INT DEFAULT 0  
    )");

    sqlconector("CREATE TABLE IF NOT EXISTS REFERIDOS (
      ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
      REFERIDO VARCHAR(34),
      REFERENTE VARCHAR(34),
      VALIDO INT NOT NULL DEFAULT 0,
      RETIRADO INT NOT NULL DEFAULT 0,
      LOGROS INT NOT NULL DEFAULT 0,
      RECOMPENSA DECIMAL(13,2) UNSIGNED NOT NULL DEFAULT 0.00)");

    sqlconector("CREATE TABLE IF NOT EXISTS USUARIOS (
        ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        IP VARCHAR(255),
        NOMBRE_USUARIO VARCHAR(25),
        PASSWORD VARCHAR(100),
        VKEY VARCHAR(100),
        CORREO VARCHAR(34),
        TELEFONO VARCHAR(15),
        NOMBRE VARCHAR(255),
        NACIONALIDAD VARCHAR(34),
        LINKREFERIDO VARCHAR(255),
        CODIGOREFERIDO VARCHAR(255),
        BEP20 VARCHAR(255),
        BINANCE VARCHAR(255),
        RATE INT NOT NULL DEFAULT 0,
        SALDO DECIMAL(13,4) UNSIGNED NOT NULL DEFAULT 0.00,
        USDT DECIMAL(13,4) UNSIGNED NOT NULL DEFAULT 0.00,
        P2P DECIMAL(13,4) UNSIGNED NOT NULL DEFAULT 0.00,
        SALDOREFERIDO DECIMAL(13,4) UNSIGNED NOT NULL DEFAULT 0.00,
        VERIFICADO INT NOT NULL DEFAULT 0,
        ACTIVO INT NOT NULL DEFAULT 0,
        LABORANDO INT NOT NULL DEFAULT 0,
        BLOQUEADO INT NOT NULL DEFAULT 0,
        NIVEL INT NOT NULL DEFAULT 0,
        ACTIVE_BEP20 INT NOT NULL DEFAULT 0,
        ACTIVE_BINANCE INT NOT NULL DEFAULT 0,
        QR_BEP20 VARCHAR(255) DEFAULT 'perfil.jpg',
        QR_BINANCE VARCHAR(255) DEFAULT 'perfil.jpg',
        PERFIL VARCHAR(255) DEFAULT 'perfil.jpg')");

    sqlconector("CREATE TABLE IF NOT EXISTS APUESTAS (
        ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        IDJUEGO INT(11),        
        TICKET TEXT,        
        FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        INICIO DATE DEFAULT CURRENT_DATE,
        FIN DATE DEFAULT CURRENT_DATE,
        TIPO VARCHAR(35),        
        JUEGO VARCHAR(255),        
        CAJERO VARCHAR(35),
        CLIENTE VARCHAR(35),   
        PORCIENTO INT(11),
        MONTO DECIMAL(16,6) NOT NULL DEFAULT 0.00,
        INTERES_MENSUAL DECIMAL(13,6) NOT NULL DEFAULT 0.00,        
        CUOTA_MENSUAL DECIMAL(13,6) NOT NULL DEFAULT 0.00,        
        TOTAL_PAGAR DECIMAL(13,6) NOT NULL DEFAULT 0.00,
        COMISION DECIMAL(13,6) NOT NULL DEFAULT 0.00,
        N_PAGOS INT NOT NULL DEFAULT 0,
        PAGADOS INT NOT NULL DEFAULT 0,
        ACTIVO INT NOT NULL DEFAULT 1,
        DEVUELVE_CAPITAL INT NOT NULL DEFAULT 0,
        ELIMINADO INT NOT NULL DEFAULT 0,
        ESTATUS VARCHAR(35) DEFAULT 'ACTIVO',
        IMAGEN VARCHAR(255) DEFAULT 'azul.png',
        FOREGROUND VARCHAR(34) DEFAULT 'white'
        MONEDA VARCHAR(20) DEFAULT 'USDC')");

    sqlconector("CREATE TABLE IF NOT EXISTS TRANSACCIONES (
      ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
      FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      TICKET TEXT,
      TIPO VARCHAR(35) DEFAULT 'DEPOSITO',
      DESCRIPCION VARCHAR(255),
      CAJERO VARCHAR(35),
      CLIENTE VARCHAR(35),
      MEDIO_PAGO VARCHAR(35) DEFAULT 'BINANCE PAY',     
      WALLET VARCHAR(255),
      ORIGEN VARCHAR(255),
      DESTINO VARCHAR(255),
      NOTAID VARCHAR(255),
      RESULTADO VARCHAR(255),
      REFERENCIA VARCHAR(255),
      MONTO DECIMAL(16,6) NOT NULL DEFAULT 0.00,
      RECIBE DECIMAL(16,6) NOT NULL DEFAULT 0.00,
      COMISION DECIMAL(13,6) NOT NULL DEFAULT 0.00,
      PAGADO INT NOT NULL DEFAULT 0,
      ENVIADO INT NOT NULL DEFAULT 0,
      ELIMINADO INT NOT NULL DEFAULT 0,
      TOMADO INT NOT NULL DEFAULT 0,
      RATE INT NOT NULL DEFAULT 0,
      CALIFICADO INT NOT NULL DEFAULT 0,
      ESTATUS VARCHAR(35) DEFAULT 'REVISION',
      MONEDA VARCHAR(20) DEFAULT 'USDC')");        

    sqlconector("CREATE TABLE IF NOT EXISTS LIBROCONTABLE (
        ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        FECHA DATE,
        TICKET TEXT,
        TIPO VARCHAR(35) DEFAULT 'CREDITO',
        IDJUEGO INT(11),
        JUEGO VARCHAR(255),        
        CAJERO VARCHAR(35),
        CLIENTE VARCHAR(35),
        MONTO DECIMAL(16,6) NOT NULL DEFAULT 0.00,
        INTERES_MENSUAL DECIMAL(13,6) NOT NULL DEFAULT 0.00,        
        CUOTA_MENSUAL DECIMAL(13,6) NOT NULL DEFAULT 0.00,        
        TOTAL_PAGAR DECIMAL(13,6) NOT NULL DEFAULT 0.00,
        COMISION DECIMAL(13,6) NOT NULL DEFAULT 0.00,
        INVERSION INT NOT NULL DEFAULT 0,
        INTERES_ADELANTADO INT NOT NULL DEFAULT 0,
        PAGADO INT NOT NULL DEFAULT 0,
        ACTIVO INT NOT NULL DEFAULT 1,
        DEVUELVE_CAPITAL INT NOT NULL DEFAULT 0,
        ELIMINADO INT NOT NULL DEFAULT 0,
        ESTATUS VARCHAR(35) DEFAULT 'ACTIVO',
        MONEDA VARCHAR(4) DEFAULT 'USDC')");

    sqlconector("CREATE TABLE IF NOT EXISTS PROMO (
        ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CODIGO TEXT,
        NOMBRE VARCHAR(34),
        MENSAJE TEXT,
        COLORBG VARCHAR(34),
        COLORFG VARCHAR(34),
        BORDER  VARCHAR(34),
        NUMPROMO INT NOT NULL DEFAULT 0,
        PREMIO DECIMAL(10,4) NOT NULL DEFAULT 0.000000,
        VISIBLE INT NOT NULL DEFAULT 0,
        GANADOR INT NOT NULL DEFAULT 0,
        DIFUSION INT NOT NULL DEFAULT 0,
        FLOTANTE INT NOT NULL DEFAULT 0)");

    sqlconector("CREATE TABLE IF NOT EXISTS USERPROMO (
        ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        CODIGO TEXT,
        CORREO VARCHAR(34),
        RATE INT NOT NULL DEFAULT 0,
        NUMREF INT NOT NULL DEFAULT 0,
        NUMPROMO INT NOT NULL DEFAULT 0)");

  sqlconector("CREATE TABLE IF NOT EXISTS LISTA (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CORREO VARCHAR(34),
    ENVIADO INT NOT NULL DEFAULT 0)");

  sqlconector("CREATE TABLE IF NOT EXISTS ENVIOLISTA (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ENVIADO INT NOT NULL DEFAULT 0)");

    sqlconector("CREATE TABLE IF NOT EXISTS JUEGOS (
        ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        JUEGO VARCHAR(255),
        DESCRIPCION TEXT,
        ANALISIS TEXT,
        CAJERO VARCHAR(35),
        TIPO VARCHAR(35),
        WALLET VARCHAR(200),
        REFERENCIA VARCHAR(100),
        PORCIENTO INT(11),
        MONTO DECIMAL(16,6) NOT NULL DEFAULT 0.00,
        COMISION DECIMAL(13,6) NOT NULL DEFAULT 0.00,        
        MIN INT NOT NULL DEFAULT 10,
        MAX INT NOT NULL DEFAULT 0,
        RATE INT NOT NULL DEFAULT 0,
        BLOQUEADO INT NOT NULL DEFAULT 0,
        VISIBLE INT NOT NULL DEFAULT 0,
        ESTATUS VARCHAR(34) DEFAULT 'ACTIVO',
        PORADELANTADO INT NOT NULL DEFAULT 0,
        FAVORITO INT NOT NULL DEFAULT 0,
        ELIMINADO INT NOT NULL DEFAULT 0,
        ACTIVO INT NOT NULL DEFAULT 1,
        DEVUELVE_CAPITAL INT NOT NULL DEFAULT 0,
        IMAGEN VARCHAR(255) DEFAULT 'azul.png',
        FOREGROUND VARCHAR(34) DEFAULT 'white'
        MONEDA VARCHAR(20) DEFAULT 'USDC')");

  sqlconector("CREATE TABLE IF NOT EXISTS CHAT (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,    
    IDPEDIDO VARCHAR(80),    
    AMO VARCHAR(34),
    ENVIA VARCHAR(34),
    RECIBE VARCHAR(34),
    MENSAJE TEXT,
    ACTIVO INT DEFAULT 0,
    LEIDO INT DEFAULT 0,
    CERRADO INT DEFAULT 0,
    BG VARCHAR(34) DEFAULT '#DEEEF3',
    FG VARCHAR(34) DEFAULT '#4D4D4D')");

sqlconector("CREATE TABLE IF NOT EXISTS LINKS (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  LINK VARCHAR(255),
  CORREO VARCHAR(255),
  BLOQUEADO INT NOT NULL DEFAULT 0)");

  
sqlconector("CREATE TABLE NOTIFICACIONES (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  IDPEDIDO VARCHAR(80),
  FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,    
  IDUSUARIO bigint(20) DEFAULT NULL,
  UBICACION varchar(200) DEFAULT NULL,
  NOTICIA text DEFAULT NULL,
  BG varchar(255) DEFAULT '#FFC0CB',
  FG varchar(255) DEFAULT '#1A1A1A',
  VISTO int(11) NOT NULL DEFAULT 0,
  BLOQUEADO int(11) NOT NULL DEFAULT 0) ");

  //FIN DE LA INSTALACION
  echo "Tablas Creada Con Exito..!<br><br><a href='index'>Ir al Inicio</a>";
}

?>