<?php

/*$servidor = "bbetfootball.online";
$user = "bbetxfub_admin";
$password = ",NN7QZ.03g+b";
$database = "bbetxfub_data";*/

$servidor = "localhost";
$user = "root";
$password = "";
$database = "apuestas";

$data = ""; 
$usuario = "";

function sqlconector($consulta) {
   $conexion = @mysqli_connect($GLOBALS["servidor"],$GLOBALS["user"],$GLOBALS["password"],$GLOBALS["database"]);
   if (!$conexion) {
     echo "Refresh page, Failed to connect to Data: " . mysqli_connect_error();
     exit();
   }else{
     $resultado = mysqli_query( $conexion, $consulta );
     mysqli_close($conexion);
   }
   return $resultado;
}

function row_sqlconector($consulta) {
  $row = array();
	$conexion = @mysqli_connect($GLOBALS["servidor"],$GLOBALS["user"],$GLOBALS["password"],$GLOBALS["database"]);
  if (!$conexion) {
    echo "Refresh page, Failed to connect to Data: " . mysqli_connect_error();
    exit();
  }else{
    $resultado = mysqli_query($conexion, $consulta);
    if($resultado){
  		$row = mysqli_fetch_array($resultado, MYSQLI_ASSOC);
  	}
  	mysqli_close($conexion);
  }
	return $row;
}

/*ALTER TABLE JUEGOS ADD COLUMN DESAFIO INT NOT NULL DEFAULT 0
  ALTER TABLE JUEGOS ADD COLUMN DESAFIOX1_5 INT NOT NULL DEFAULT 0
  ALTER TABLE JUEGOS ADD COLUMN DESAFIOX3 INT NOT NULL DEFAULT 0
  ALTER TABLE JUEGOS ADD COLUMN FAVORITO INT NOT NULL DEFAULT 0
*/
if( isset($_GET['parche']) ){
/* APLICA MODIFICACIONES DE ULTIMA HORA A LA BASE DE DATOS Y SISTEMA
ESCRIBE AQUI LA LOGICA..
*/  

  echo "Parche Aplicado Con Exito..!<br><br><a href='index'>Ir al Inicio</a>";
}

if( isset($_GET['install']) ){
    sqlconector("CREATE TABLE IF NOT EXISTS REFERIDOS (
      ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
      REFERIDO VARCHAR(34),
      REFERENTE VARCHAR(34),
      VALIDO INT NOT NULL DEFAULT 0,
      RETIRADO INT NOT NULL DEFAULT 0,
      LOGROS INT NOT NULL DEFAULT 0,
      RECOMPENSA DECIMAL(13,2) UNSIGNED NOT NULL DEFAULT 0.00)");

    sqlconector("CREATE TABLE IF NOT EXISTS USUARIOS (
        ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        IP VARCHAR(255),
        NOMBRE_USUARIO VARCHAR(25),
        PASSWORD VARCHAR(100),
        VKEY VARCHAR(100),
        CORREO VARCHAR(34),
        TELEFONO VARCHAR(15),
        NOMBRE VARCHAR(255),
        NACIONALIDAD VARCHAR(34),
        LINKREFERIDO VARCHAR(255),
        CODIGOREFERIDO VARCHAR(255),
        WALLET VARCHAR(255),
        PAYEER VARCHAR(255),
        BINANCE VARCHAR(255),
        AIRTM VARCHAR(255),
        RATE INT NOT NULL DEFAULT 0,
        SALDO DECIMAL(13,4) UNSIGNED NOT NULL DEFAULT 0.00,
        USDT DECIMAL(13,4) UNSIGNED NOT NULL DEFAULT 0.00,
        P2P DECIMAL(13,4) UNSIGNED NOT NULL DEFAULT 0.00,
        SALDOREFERIDO DECIMAL(13,4) UNSIGNED NOT NULL DEFAULT 0.00,
        VERIFICADO INT NOT NULL DEFAULT 0,
        ACTIVO INT NOT NULL DEFAULT 0,
        BLOQUEADO INT NOT NULL DEFAULT 0,
        NIVEL INT NOT NULL DEFAULT 0,
        PERFIL VARCHAR(255) DEFAULT 'perfil.jpg')");

    sqlconector("CREATE TABLE IF NOT EXISTS APUESTAS (
        ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        TICKET TEXT,
        TIPO VARCHAR(35),
        APUESTA VARCHAR(255),
        JUEGO VARCHAR(255),        
        CAJERO VARCHAR(35),
        CLIENTE VARCHAR(35),   
        MEDIO_PAGO VARCHAR(35),     
        WALLET TEXT,
        NOTAID TEXT,
        RESULTADO TEXT,
        REFERENCIA TEXT,
        MONTO DECIMAL(16,6) NOT NULL DEFAULT 0.00,
        RECIBE DECIMAL(16,6) NOT NULL DEFAULT 0.00,
        COMISION DECIMAL(13,6) NOT NULL DEFAULT 0.00,
        PAGADO INT NOT NULL DEFAULT 0,
        ENVIADO INT NOT NULL DEFAULT 0,
        ELIMINADO INT NOT NULL DEFAULT 0,
        TOMADO INT NOT NULL DEFAULT 0,
        ESTATUS VARCHAR(35),
        MONEDA VARCHAR(20) DEFAULT 'USDT')");

    sqlconector("CREATE TABLE IF NOT EXISTS TRANSACCIONES (
      ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
      FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      TICKET TEXT,
      TIPO VARCHAR(35) DEFAULT 'DEPOSITO',
      DESCRIPCION VARCHAR(255),
      CAJERO VARCHAR(35),
      CLIENTE VARCHAR(35),
      MEDIO_PAGO VARCHAR(35) DEFAULT 'BINANCE PAY',     
      WALLET VARCHAR(255),
      NOTAID VARCHAR(255),
      RESULTADO VARCHAR(255),
      REFERENCIA VARCHAR(255),
      MONTO DECIMAL(16,6) NOT NULL DEFAULT 0.00,
      RECIBE DECIMAL(16,6) NOT NULL DEFAULT 0.00,
      COMISION DECIMAL(13,6) NOT NULL DEFAULT 0.00,
      PAGADO INT NOT NULL DEFAULT 0,
      ENVIADO INT NOT NULL DEFAULT 0,
      ELIMINADO INT NOT NULL DEFAULT 0,
      TOMADO INT NOT NULL DEFAULT 0,
      ESTATUS VARCHAR(35) DEFAULT 'EN PROCESO',
      MONEDA VARCHAR(20) DEFAULT 'USDC')");        

    sqlconector("CREATE TABLE IF NOT EXISTS LIBROCONTABLE (
        ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        OPERACION VARCHAR(4) DEFAULT 'COMI',
        TIPO VARCHAR(34),
        MONTO DECIMAL(10,4) NOT NULL DEFAULT 0.000000,
        DEVUELTO INT NOT NULL DEFAULT 0,
        ESTATUS VARCHAR(34) DEFAULT 'PAGADO',
        MONEDA VARCHAR(4) DEFAULT 'USDT')");

    sqlconector("CREATE TABLE IF NOT EXISTS PROMO (
        ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CODIGO TEXT,
        NOMBRE VARCHAR(34),
        MENSAJE TEXT,
        COLORBG VARCHAR(34),
        COLORFG VARCHAR(34),
        BORDER  VARCHAR(34),
        NUMPROMO INT NOT NULL DEFAULT 0,
        PREMIO DECIMAL(10,4) NOT NULL DEFAULT 0.000000,
        VISIBLE INT NOT NULL DEFAULT 0,
        GANADOR INT NOT NULL DEFAULT 0,
        DIFUSION INT NOT NULL DEFAULT 0,
        FLOTANTE INT NOT NULL DEFAULT 0)");

    sqlconector("CREATE TABLE IF NOT EXISTS USERPROMO (
        ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        CODIGO TEXT,
        CORREO VARCHAR(34),
        RATE INT NOT NULL DEFAULT 0,
        NUMREF INT NOT NULL DEFAULT 0,
        NUMPROMO INT NOT NULL DEFAULT 0)");

  sqlconector("CREATE TABLE IF NOT EXISTS LISTA (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CORREO VARCHAR(34),
    ENVIADO INT NOT NULL DEFAULT 0)");

  sqlconector("CREATE TABLE IF NOT EXISTS ENVIOLISTA (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ENVIADO INT NOT NULL DEFAULT 0)");

    sqlconector("CREATE TABLE IF NOT EXISTS JUEGOS (
        ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        INICIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FIN TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        JUEGO VARCHAR(255),
        EQUIPO1 VARCHAR(35),
        EQUIPO2 VARCHAR(35),
        CAJERO VARCHAR(35),
        TIPO VARCHAR(35),
        WALLET TEXT,
        REFERENCIA TEXT,
        COMISION DECIMAL(13,6) NOT NULL DEFAULT 0.00,        
        MIN INT NOT NULL DEFAULT 10,
        MAX INT NOT NULL DEFAULT 10,
        RATE INT NOT NULL DEFAULT 0,
        BLOQUEADO INT NOT NULL DEFAULT 0,
        VISIBLE INT NOT NULL DEFAULT 0,
        ESTATUS VARCHAR(34),
        APUESTAS INT NOT NULL DEFAULT 0,
        DESAFIO INT NOT NULL DEFAULT 0,
        DESAFIOX1_5 INT NOT NULL DEFAULT 0,
        DESAFIOX3 INT NOT NULL DEFAULT 0,
        FAVORITO INT NOT NULL DEFAULT 0,
        ELIMINADO INT NOT NULL DEFAULT 0,
        MONEDA VARCHAR(20) DEFAULT 'USDT')");

  sqlconector("CREATE TABLE IF NOT EXISTS CHAT (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TICKED VARCHAR(80),
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    AMO VARCHAR(34),
    ENVIA VARCHAR(34),
    RECIBE VARCHAR(34),
    MENSAJE TEXT,
    ACTIVO INT DEFAULT 0,
    LEIDO INT DEFAULT 0,
    CERRADO INT DEFAULT 0,
    BG VARCHAR(34) DEFAULT '#DEEEF3',
    FG VARCHAR(34) DEFAULT '#4D4D4D')");
    echo "Tablas Creada Con Exito..!<br><br><a href='index'>Ir al Inicio</a>";
}

?>